### ISSUE TITLE
How do I use the `-H` or `--sha1` flags with this library?

### ISSUE THREAD

**Issue by EmmaCruz94** [kherrick/pwgen#3]
The original `pwgen` lets me pass a file or string as a seed.

Example:

```bash
pwgen 16 1 -H <(echo "foobar")
```

Is this possible with your JavaScript implementation of `pwgen`? 

Or is it possible to use a file with our implementation -even with a DATAURI?

**Comment by kherrick** [comment]
Thank you for the report. It looks like the value provided to the option needed to be passed to [the original pwgen](https://github.com/tytso/pwgen/tree/1459a31e07fa208cddb2c4f3f72071503c37b8bc) using a [file system with Emscripten](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-memfs). This is now possible in node with pwgen@[1.2.6](https://github.com/kherrick/pwgen/releases/tag/1.2.6).

```bash
$ npx pwgen@1.2.6 16 1 -H <(echo "foobar")
yooh5je9Eephuthi
```
